# Generated by Django 4.2 on 2023-04-16 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0003_alter_personal_user_alter_student_student_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_management.personal'),
        ),
    ]
