# Generated by Django 4.2 on 2023-04-17 18:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0004_remove_personal_courses_course_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assginment',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='final_exam',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='midterm_exam',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='practice',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='_class',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=2002),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='student_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_no',
            field=models.CharField(default='0000002343', max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_management.student')),
            ],
        ),
    ]
