# Generated by Django 4.2 on 2023-04-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0005_course_assginment_course_final_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='project',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
