# Generated by Django 4.2 on 2023-04-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0008_course__class_course_course_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('2023 Spring Semester', '2023 Spring Semester'), ('2023 Fall Semester', '2023 Fall Semester')], max_length=30),
        ),
    ]
