# Generated by Django 4.2 on 2023-04-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0009_alter_course_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='MYAZ230', max_length=15),
        ),
    ]
