# Generated by Django 4.2 on 2023-04-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0011_rename__class_course_class_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('Spring Semester', 'Spring Semester'), ('Fall Semester', 'Fall Semester')], max_length=30),
        ),
    ]
