# Generated by Django 4.2 on 2023-04-20 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0012_alter_course_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOutcomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math_science', models.IntegerField()),
                ('engineering_science', models.IntegerField()),
                ('engineering_design', models.IntegerField()),
                ('liberal_arts', models.IntegerField()),
                ('educational_science', models.IntegerField()),
                ('science', models.IntegerField()),
                ('health_science', models.IntegerField()),
                ('area_information', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_no', models.IntegerField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('document', models.FileField(default='default.pdf', upload_to='course_plan_files')),
                ('w02_doc', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('reference_address', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='aim_of_lesson',
            field=models.TextField(default=1991),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_assistants',
            field=models.ManyToManyField(related_name='assistants', to='course_management.personal'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_content',
            field=models.TextField(default=2017),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_language',
            field=models.CharField(choices=[('English', 'English'), ('Turkish', 'Turkish')], default='Turkish', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='course_level',
            field=models.CharField(choices=[('associate degree', 'associate degree'), ('licence', 'licence'), ('master degree', 'master degree'), ('doc', 'doc')], default='licence', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='course_learning_outcomes',
            field=models.ManyToManyField(to='course_management.courseoutcomes'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_resources',
            field=models.ManyToManyField(to='course_management.resource'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_management.coursestructure'),
        ),
    ]
