# Generated by Django 4.2 on 2023-04-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0013_courseoutcomes_coursestructure_coursetopics_resource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetopics',
            name='week_no',
            field=models.IntegerField(),
        ),
    ]
