# Generated by Django 4.2 on 2023-04-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0014_alter_coursetopics_week_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_assistants',
            field=models.ManyToManyField(blank=True, null=True, related_name='assistants', to='course_management.personal'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_no',
            field=models.CharField(default='0000002344', max_length=10, unique=True),
        ),
    ]
