# Generated by Django 4.2 on 2023-04-22 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0015_alter_course_course_assistants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_structure',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course_management.coursestructure'),
        ),
    ]
