# Generated by Django 4.2 on 2023-04-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0017_alter_coursestructure_area_information_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_no', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14')])),
                ('topic', models.CharField(max_length=255)),
                ('document', models.FileField(blank=True, null=True, upload_to='course_plan_files')),
            ],
        ),
        migrations.DeleteModel(
            name='CourseTopics',
        ),
        migrations.AddField(
            model_name='course',
            name='coruse_topics',
            field=models.ManyToManyField(to='course_management.coursetopic'),
        ),
    ]
