# Generated by Django 4.2 on 2023-04-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0021_alter_coursetopic_week_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester_no',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], default=1),
        ),
    ]
