# Generated by Django 4.2 on 2023-05-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0022_course_semester_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='_class',
            new_name='class_no',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_no',
            field=models.CharField(default='0000002359', max_length=10, unique=True),
        ),
    ]
