# Generated by Django 4.2 on 2023-05-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0024_alter_course_lecturer_alter_student_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_assistants',
            field=models.ManyToManyField(blank=True, related_name='assistants', to='course_management.personal'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_topics',
            field=models.ManyToManyField(blank=True, to='course_management.coursetopic'),
        ),
    ]
