# Generated by Django 4.2 on 2023-05-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0025_alter_course_course_assistants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_document',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
