# Generated by Django 4.2 on 2023-05-17 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0027_alter_coursetopic_week_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='assginment',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='final_exam',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='midterm_exam',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='practice',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='project',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_no',
            field=models.CharField(default='0000023511', max_length=10, unique=True),
        ),
    ]
