# Generated by Django 4.2 on 2023-05-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0031_alter_mark_course_alter_mark_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='exam_doc',
            field=models.FileField(blank=True, null=True, upload_to='exam_documents'),
        ),
    ]
