# Generated by Django 4.2 on 2023-05-20 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0032_mark_exam_doc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='class_no',
            new_name='class_info',
        ),
    ]
