# Generated by Django 4.2 on 2023-05-20 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0034_rename_class_info_course_class_no_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='teacher',
        ),
    ]
