# Generated by Django 4.2 on 2023-05-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0035_remove_classroom_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='lecture_start_time',
            field=models.DurationField(),
        ),
    ]
