# Generated by Django 4.2 on 2023-05-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0036_alter_classroom_lecture_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='lecture_start_time',
            new_name='lecture_time',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='lecture_end_time',
        ),
    ]
