# Generated by Django 4.2 on 2023-05-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0039_alter_classroom_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='lecture_time',
            field=models.CharField(choices=[('09:00am-09:45am', '09:00am-09:45am'), ('10:00am-10:45am', '10:00am-10:45am'), ('11:00am-11:45am', '11:00am-11:45am'), ('01:00pm-01:45pm', '01:00pm-01:45pm'), ('02:00pm-02:45pm', '02:00pm-02:45pm'), ('02:00pm-02:45pm', '02:00pm-02:45pm'), ('03:00pm-03:45pm', '03:00pm-03:45pm'), ('04:00pm-04:45pm', '04:00pm-04:45pm')], max_length=50),
        ),
    ]
