# Generated by Django 4.2 on 2023-05-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0040_alter_classroom_lecture_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=30),
        ),
    ]
