# Generated by Django 4.2 on 2023-05-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0042_alter_classroom_day_alter_student_academic_advisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_no',
            field=models.CharField(default='0000023511', max_length=10, unique=True),
        ),
    ]
