# Generated by Django 4.2 on 2023-05-21 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0044_alter_course_course_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='final_exam',
            field=models.IntegerField(blank=True, default=60, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='midterm_exam',
            field=models.IntegerField(blank=True, default=40, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
