# Generated by Django 4.2 on 2023-05-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0046_alter_student_student_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(blank=True, choices=[('Spring Semester', 'Spring Semester'), ('Fall Semester', 'Fall Semester')], max_length=30, null=True),
        ),
    ]
